version: 3
endpoint: https://clever-amoeba-41.hasura.app
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: migrations
seeds_directory:seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: https://clever-amoeba-41.hasura.app
